version: '3' 

services: 
  go-micro: 
    build: 
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile 
    restart: always  
    ports: 
      - "8087:80" 
    deploy:
      mode: replicated
      replicas: 1 


  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    restart: always
    ports:
      - "8086:80"
    deploy:
      mode: replicated
      replicas: 1    
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=authdb sslmode=disable timezone=UTC connect_timeout=5"


  postgres: 
    image: 'postgres:alpine' 
    ports: 
      - "5432:5432" 
    restart: always
    deploy:
      mode: replicated
      replicas: 1  
    environment: 
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=password 
      - POSTGRES_DB=authdb 

    volumes: 
      - ./database/postgres:/var/lib/postgresql/data  