version: '3' 

services: 
  go-micro: 
    build: 
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile 
    restart: always  
    ports: 
      - "8087:80" 
    deploy:
      mode: replicated
      replicas: 1
